LAB 10 21 April, 2026

In [87]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [88]:
data = pd.read_csv("Stars.csv")
data.head()

   Temperature         L       R    A_M Color Spectral_Class  Type
0         3068  0.002400  0.1700  16.12   Red              M     0
1         3042  0.000500  0.1542  16.60   Red              M     0
2         2600  0.000300  0.1020  18.70   Red              M     0
3         2800  0.000200  0.1600  16.65   Red              M     0
4         1939  0.000138  0.1030  20.06   Red              M     0

1. Separate out the categorical and numerical columns in dataset.

In [89]:
num = data.select_dtypes(include=[np.number])
cat = data.select_dtypes(exclude=[np.number])

num.head()

   Temperature         L       R    A_M  Type
0         3068  0.002400  0.1700  16.12     0
1         3042  0.000500  0.1542  16.60     0
2         2600  0.000300  0.1020  18.70     0
3         2800  0.000200  0.1600  16.65     0
4         1939  0.000138  0.1030  20.06     0

In [90]:
cat.head()

  Color Spectral_Class
0   Red              M
1   Red              M
2   Red              M
3   Red              M
4   Red              M

2. For each numeric attribute replace missing value with next value in records (row wise).and Perform Max-Min Normalization on each attribute and scale them in the range of 0-1.

In [91]:
# for col in num.columns:
#     num[col] = num[col].bfill().ffill()

# or

for col in num.columns:
    n = len(num[col])
    for i in range(n):
        if pd.isna(num.iloc[i][col]):
            j = i + 1
            while j < n and pd.isna(num.iloc[j][col]):
                j += 1
            if j < n:
                num.loc[i, col] = num.loc[j, col]

In [92]:
for col in num.columns:
    x_max = num[col].max()
    x_min = num[col].min()

    if x_max != x_min:
        num[col] = (num[col] - x_min) / (x_max - x_min)
    
num.head()

   Temperature             L         R       A_M  Type
0     0.029663  2.731275e-09  0.000083  0.876798   0.0
1     0.028980  4.944550e-10  0.000075  0.891807   0.0
2     0.017367  2.590003e-10  0.000048  0.957473   0.0
3     0.022622  1.412729e-10  0.000078  0.893371   0.0
4     0.000000  6.828189e-11  0.000049  1.000000   0.0

3. Label Encode all the categorical attributes except the class label.

In [98]:
for col in cat:
    cat[col] = cat[col].astype('category').cat.codes

cat

     Color  Spectral_Class
0        8               5
1        8               5
2        8               5
3        8               5
4        8               5
..     ...             ...
235      0               6
236      0               6
237      9               0
238      9               0
239      0               6

[240 rows x 2 columns]

4. Fit the Logistic Regression Classifier with 70% Training Data.

In [94]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import classification_report

In [95]:
y = num.iloc[:, -1]
num.drop('Type', axis = 1)
dataset = num.iloc[:, :-1].join(cat)
X = dataset.iloc[:, :]

In [96]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=42)

In [97]:
model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
acc = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
print("Accuracy: ", acc)

print("\n============REPORT=================")

print(report)

ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 0  0 14  0  0  0]
 [ 0  0 12  0  0  0]
 [ 0  0 10  0  0  0]
 [ 0  0  4  5  1  0]
 [ 0  0  0  1 10  0]
 [ 0  0  0  0  0 15]]

5. Find the least amount of training data required to get the best accuracy of 1.0 in Logistic regression classifier.

6. Do we need all the attributes to get the best accuracy. Fit the classifier with different Permutations of features and determine the best feature set to get the maximum accuracy.

7.Fit the SVM Classifier and determine the best learning rate at which maximum accuracy is achieved with least amount of training data. Plot amount of training data vs learning rate.